package fr.uge.univ_eiffel.image_processing;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.ArrayList;
import javax.imageio.ImageIO;

public class LegoVisualizer {

    public static void main(String[] args) throws IOException {

        if (args.length < 2) {
            System.err.println("Usage: LegoVisualizer <inputPathTxt> <outputPathPng>");
            return;
        }
        String inputTxtPath = args[0];
        String outputPngPath = args[1];

        BufferedReader reader = new BufferedReader(new FileReader(inputTxtPath));
        String line;

        int maxX = 0;
        int maxY = 0;

        ArrayList<String[]> squareBricks = new ArrayList<>();

        while ((line = reader.readLine()) != null) {
            if (line.isBlank() || line.startsWith("[")) continue;

            try {
                String[] parts = line.split(",");
                // Expected format: w-h/hexval,rotation,x,y

                String[] typeParts = parts[0].split("/");
                String[] dims = typeParts[0].split("-");
                String hexColor = typeParts[1];

                int rawW = Integer.parseInt(dims[0].trim());
                int rawH = Integer.parseInt(dims[1].trim());
                int rotation = Integer.parseInt(parts[1].trim());
                int x = Integer.parseInt(parts[2].trim());
                int y = Integer.parseInt(parts[3].trim());

                int w = rawW;
                int h = rawH;

                if (rotation == 1) {
                    w = rawH;
                    h = rawW;
                }

                maxX = Math.max(maxX, x + w);
                maxY = Math.max(maxY, y + h);
                squareBricks.add(new String[]{String.valueOf(w), String.valueOf(h), hexColor, String.valueOf(x), String.valueOf(y)});
            } catch (Exception e) {
                // Print malformed lines to help debug C output
                System.err.println("Skipped invalid line: " + line);
            }
        }
        reader.close();

        if (squareBricks.isEmpty()) {
            System.err.println("Error: No bricks were generated by the C program.");
            System.err.println("Check if 'catalog.txt' exists and if the image has compatible colors.");
            System.exit(1);
        }

        int scale = Math.max(1, Math.min(10, 5000 / Math.max(1, Math.max(maxX, maxY))));

        BufferedImage image = new BufferedImage(maxX * scale, maxY * scale, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = image.createGraphics();

        for (String[] brick : squareBricks) {
            int w = Integer.parseInt(brick[0]);
            int h = Integer.parseInt(brick[1]);
            int x = Integer.parseInt(brick[3]);
            int y = Integer.parseInt(brick[4]);
            Color brickColor = Color.decode("#" + brick[2]);
            Color brickEdge = new Color(0, 0, 0, 50);
            Color studColor = brickColor.brighter();
            Color studEdge = new Color(0, 0, 0, 50);

            g.setColor(brickColor);
            g.fillRect(x * scale, y * scale, w * scale, h * scale);
            g.setColor(brickEdge);
            g.drawRect(x * scale, y * scale, w * scale, h * scale);

            for (int i = 0; i < w; i++) {
                for (int j = 0; j < h; j++) {
                    int studX = (x + i) * scale;
                    int studY = (y + j) * scale;
                    int padding = scale / 5;

                    g.setColor(studColor);
                    g.fillOval(studX + padding, studY + padding, scale - padding*2, scale - padding*2);
                    g.setColor(studColor);
                    g.fillOval(studX + padding, studY + padding, scale - padding*2, scale - padding*2);
                    g.setColor(studEdge);
                    g.drawOval(studX + padding, studY + padding, scale - padding*2, scale - padding*2);
                }
            }
        }
        g.dispose();

        ImageIO.write(image, "png", new File(outputPngPath + ".png"));
        System.out.println("Visualized PNG saved.");
    }
}