package image_processing;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.ArrayList;
import javax.imageio.ImageIO;

public class LegoVisualizer {

    public static void main(String[] args) throws IOException {

        if (args.length < 2) {
            System.err.println("Usage: LegoVisualizer <input_txt> <output_png>");
            return;
        }
        String inputTxtPath = args[0];
        String outputPngPath = args[1];

        BufferedReader reader = new BufferedReader(new FileReader(inputTxtPath));
        String line;

        int maxX = 0;
        int maxY = 0;

        ArrayList<String[]> squareBricks = new ArrayList<>();

        while ((line = reader.readLine()) != null) {
            if (line.isBlank()) continue;

            try {
                String[] parts = line.split(",");
                // Expected format: 2x4-Red/FF0000, 10, 20
                // Adjust if your C output is different!
                String[] brickName = parts[0].split("/");
                String[] dims = brickName[0].split("-");

                int x = Integer.parseInt(parts[1]);
                int y = Integer.parseInt(parts[2]);
                int w = Integer.parseInt(dims[0]);
                int h = Integer.parseInt(dims[1]);

                maxX = Math.max(maxX, x + w);
                maxY = Math.max(maxY, y + h);
                squareBricks.add(new String[]{dims[0], dims[1], brickName[1], parts[1], parts[2]});
            } catch (Exception e) {
                // Print malformed lines to help debug C output
                System.err.println("Skipped invalid line: " + line);
            }
        }
        reader.close();

        // ⚡ FIX: Handle empty result to prevent crash
        if (squareBricks.isEmpty()) {
            System.err.println("Error: No bricks were generated by the C program.");
            System.err.println("Check if 'catalog.txt' exists and if the image has compatible colors.");
            // Create a dummy 1x1 image so we don't crash, or just exit
            System.exit(1);
        }

        int scale = 10;
        // Now safe to create image
        BufferedImage image = new BufferedImage(maxX * scale, maxY * scale, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = image.createGraphics();

        for (String[] brick : squareBricks) {
            int w = Integer.parseInt(brick[0]);
            int h = Integer.parseInt(brick[1]);
            int x = Integer.parseInt(brick[3]);
            int y = Integer.parseInt(brick[4]);
            Color brickColor = Color.decode("#" + brick[2]).darker();
            Color brickEdge = new Color(0, 0, 0);
            Color studColor = brickColor.brighter();
            Color studEdge = new Color(0, 0, 0, 50);

            g.setColor(brickColor);
            g.fillRect(x * scale, y * scale, w * scale, h * scale);
            g.setColor(brickEdge);
            g.drawRect(x * scale, y * scale, w * scale, h * scale);

            for (int i = 0; i < w; i++) {
                for (int j = 0; j < h; j++) {
                    int studX = (x + i) * scale;
                    int studY = (y + j) * scale;
                    int padding = scale / 5;

                    g.setColor(studColor);
                    g.fillOval(studX + padding, studY + padding, scale - padding*2, scale - padding*2);
                    g.setColor(studColor);
                    g.fillOval(studX + padding, studY + padding, scale - padding*2, scale - padding*2);
                    g.setColor(studEdge);
                    g.drawOval(studX + padding, studY + padding, scale - padding*2, scale - padding*2);
                }
            }
        }
        g.dispose();

        ImageIO.write(image, "png", new File(outputPngPath));
        System.out.println("Visualized PNG saved.");
    }
}